use t3 structure, set up auth

diff --git a/apps/cms/Dockerfile b/apps/cms/Dockerfile
--- a/apps/cms/Dockerfile
+++ b/apps/cms/Dockerfile
@@ -1,40 +1,55 @@
-FROM node:20-alpine AS base
+##### DEPENDENCIES
 
-# Install pnpm
-RUN npm install -g pnpm
-
-# Install dependencies (for the entire monorepo)
-FROM base AS deps
+FROM --platform=linux/amd64 node:20-alpine AS deps
+RUN apk add --no-cache libc6-compat openssl
 WORKDIR /app
-COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
-COPY apps/cms/package.json ./apps/cms/package.json
-COPY packages/db/package.json ./packages/db/package.json
-RUN pnpm install --frozen-lockfile
 
-# Development image
-FROM base AS development
+# Install dependencies based on the preferred package manager
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
+
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+##### BUILDER
+
+FROM --platform=linux/amd64 node:20-alpine AS builder
+ARG DATABASE_URL
+ARG NEXT_PUBLIC_CLIENTVAR
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-EXPOSE 3001
-CMD ["pnpm", "--filter", "cms", "dev"]
 
-# Production build
-FROM base AS builder
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN \
+    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
+    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+##### RUNNER
+
+FROM --platform=linux/amd64 gcr.io/distroless/nodejs20-debian12 AS runner
 WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
-COPY . .
-RUN pnpm build:2
 
-# Production image
-FROM base AS production
-WORKDIR /app
-ENV NODE_ENV=production
+ENV NODE_ENV production
 
-# Copy built app (assuming Next.js standalone output)
-COPY --from=builder /app/apps/cms/public ./public
-COPY --from=builder /app/apps/cms/.next/standalone ./
-COPY --from=builder /app/apps/cms/.next/static ./.next/static
+ENV NEXT_TELEMETRY_DISABLED 1
 
-EXPOSE 3001
-CMD ["node", "server.js"]
+COPY --from=builder /app/next.config.js ./
+COPY --from=builder /app/public ./public
+COPY --from=builder /app/package.json ./package.json
+
+COPY --from=builder /app/.next/standalone ./
+COPY --from=builder /app/.next/static ./.next/static
+
+EXPOSE 3000
+ENV PORT 3000
+
+CMD ["server.js"]
